'''
Copyright 2020 Infosys Ltd.
Use of this source code is governed by Apache 2.0 license that can be found in the LICENSE file or at 
https://opensource.org/licenses/Apache-2.0 .
'''
---
- name: Check if mysql exists on host server
  hosts: dbserver
  connection: ssh
  user: admin
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: check if mysql exists on host
    become: yes
    become_user: root
    shell: pgrep mysql
    ignore_errors: yes
    register: mysql_proc_status
    failed_when: "mysql_proc_status.rc == 2 or mysql_proc_status.rc == 3"
  - debug: msg="{{ mysql_proc_status.msg }}"