'''
Copyright 2020 Infosys Ltd.
Use of this source code is governed by Apache 2.0 license that can be found in the LICENSE file or at 
https://opensource.org/licenses/Apache-2.0 .
'''
---
- name: Copy files between two remote/managed nodes from a control node
  hosts: "{{ host_name }}"
  connection: ssh
  user: admin
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Copying file to the remote node
    become: yes
    become_user: root
    copy:
      src: "{{ src_file }}"
      desc: "{{ dest_file }}"
    ignore_errors: yes
    register: copy_file_status
  - debug: 
      msg: "{% if copy_file_status.changed == true %}File has been copied successfully{% else %}Could not find or access the file or the file has been already present in the remote node{% endif %}"